#!/bin/bash
 
## Bash script to backup specified index files. mlocate package required.
 
## Author: Seff Parker
## Version: 20180905
 
echo "INFO: Updating file index database..."
if ! updatedb &> /dev/null
	then
		echo "ERROR: Failed to generate search indexes! Aborting..."
		exit 1
	fi
 
BACKUP_DIR="/backup/index_htaccess/`date +%a`" # Sun to Mon (Daily in a week)
#BACKUP_DIR="/backup/index_htaccess/`date +%d`" # 01 to 31 (Daily in a month)
 
mkdir -p $BACKUP_DIR
 
SOURCE_FILES=".htaccess index.php index.html index.htm"
 
for SOURCE_FILE in $SOURCE_FILES
	do
	echo -e "INFO: Copying \"${SOURCE_FILE}\" files..."
	locate "/${SOURCE_FILE}" | grep "^/home" | grep -vE '/home.*/virtfs/|.trash' | grep ${SOURCE_FILE}$ | xargs -I {} cp -au --parents "{}" ${BACKUP_DIR}/
done
echo "INFO: Staling existing backup ${BACKUP_DIR}.tar.gz"
mv ${BACKUP_DIR}.tar.gz ${BACKUP_DIR}_staled.tar.gz
if /bin/tar -czf ${BACKUP_DIR}.tar.gz ${BACKUP_DIR}
	then echo "INFO: Removing temporary file..."
	/bin/rm -rf ${BACKUP_DIR}
	/bin/rm -f ${BACKUP_DIR}_staled.tar.gz
else
	echo "ERROR: Restoring previous backup"
	mv ${BACKUP_DIR}_staled.tar.gz ${BACKUP_DIR}.tar.gz
fi
